### ISSUE TITLE
Scalability technique S1, S2, S3 in the paper

### ISSUE THREAD

**Issue by EricTtTtT** [nimish15shah/GRAPHOPT#4]
Hi, I ran the case for pumsb_star (threads 2), the runtime is about 380 seconds while it's 183 seconds in the paper.  Despite the difference in computing resources, I want to make sure the scalability techniques are turned on.
What is the default setting for scalability techniques S1, S2, and S3 in the paper?
I guess set sub_partition_mode= 'TWO_WAY_LIMIT_LAYERS' is to apply S1.  But how about S2 and S3?

**Comment by nimish15shah** [comment]
Hi Eric,

Is this the runtime of the workload (the OpenMP execution) or the super layer generation? (I believe the later).

The super layer generation time is indeed highly compute resource-specific, especially the number of available CPU cores.

All the scalability techniques are enabled by default. You are correct that 'TWO_WAY_LIMIT_LAYERS' refers to S1. Unfortunately, we didn't get time to expose the knobs for S2 and S3 to the main file/command line.

Both the scalability techniques can be controlled in the file `./src/super_layer_generation/minizinc_top.py`. S2 can be disabled by setting `DO_NOT_CONSIDER_COMPONENTS = True` and S3 can be disabled by setting `NODES_THRESHOLD` variable to a very high value in the function `two_way_partition_get_best_result`. You can look for the comment `NOTE: CHANGE for disabling optimizations` to see the locations where scalability techniques play a role.

Another important note: There is in fact one more scalability technique S4, which we could not go into detail due to limited paper length and to keep it readable. In this technique, we use our own _local optimization-based_ routine for very small graphs instead of invoking minizinc to avoid its launch overhead. The local optimization routine is in `./src/super_layer_generation/local_optimization.py`. The technique can be disabled (if you want to see its impact) by setting `local_opt_threshold = 0` in `./src/super_layer_generation/minizinc_top.py`.

Hope this helps!

**Comment by nimish15shah** [comment]
An additional note: it is highly likely that superlayer generation takes different time on your machine because it is dependent on the number of CPU cores. The Google OR Tools solver uses multiple cores, and we ran our experiments on an Intel server CPU with 18 cores. If you have fewer cores, the generation time would be longer (irrespective of the target CPU threads, which is 2 here)

**Comment by EricTtTtT** [comment]
Got it! Thank you for the prompt reply!  I currently run it on a server CPU under a docker environment with limited 8 cores, I'll try to use more cores to speed up.
